package diagrams

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type adrLinksFile struct {
	ADRs []adrLink `yaml:"adrs"`
}

type adrLink struct {
	ADRID           string   `yaml:"adr_id"`
	LinkedServices  []string `yaml:"linked_services"`
	ImplementsSpecs []string `yaml:"implements_specs"`
}

type frontendArchitectureFile struct {
	FrontendPageArchitecture frontendPageArchitecture `yaml:"frontend_page_architecture"`
}

type frontendPageArchitecture struct {
	Nodes      []frontendNode `yaml:"nodes"`
	SharedTags []string       `yaml:"shared_tags"`
}

type frontendNode struct {
	ID    string            `yaml:"id"`
	Type  string            `yaml:"type"`
	Tags  []string          `yaml:"tags"`
	Links frontendNodeLinks `yaml:"links"`
}

type frontendNodeLinks struct {
	ContentSpec          string   `yaml:"content_spec"`
	VisualSpec           string   `yaml:"visual_spec"`
	ImplementationGuides []string `yaml:"implementation_guides"`
}

func Generate(artifactsDir, outputDir string) error {
	inputPath := filepath.Join(artifactsDir, "adr-links.yaml")
	content, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("read adr-links.yaml: %w", err)
	}

	var links adrLinksFile
	if err := yaml.Unmarshal(content, &links); err != nil {
		return fmt.Errorf("parse adr-links.yaml: %w", err)
	}
	if len(links.ADRs) == 0 {
		return fmt.Errorf("no ADR links found in %s", inputPath)
	}

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(outputDir, "01-adr-to-services.md"), []byte(renderADRToServices(links.ADRs)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outputDir, "02-adr-to-specs.md"), []byte(renderADRToSpecs(links.ADRs)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outputDir, "03-service-decision-heatmap.md"), []byte(renderServiceDecisionHeatmap(links.ADRs)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outputDir, "README.md"), []byte(renderReadme()), 0o644); err != nil {
		return err
	}

	return nil
}

func GenerateFrontend(artifactsDir, outputDir string) error {
	inputPath := filepath.Join(artifactsDir, "frontend-page-architecture-tags.yaml")
	content, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("read frontend-page-architecture-tags.yaml: %w", err)
	}

	var model frontendArchitectureFile
	if err := yaml.Unmarshal(content, &model); err != nil {
		return fmt.Errorf("parse frontend-page-architecture-tags.yaml: %w", err)
	}

	nodes := model.FrontendPageArchitecture.Nodes
	if len(nodes) == 0 {
		return fmt.Errorf("no frontend architecture nodes found in %s", inputPath)
	}

	sort.Slice(nodes, func(i, j int) bool {
		return nodes[i].ID < nodes[j].ID
	})

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	output := renderFrontendPageTagArchitecture(nodes, model.FrontendPageArchitecture.SharedTags)
	outFile := filepath.Join(outputDir, "06-frontend-page-tag-architecture.generated.md")
	if err := os.WriteFile(outFile, []byte(output), 0o644); err != nil {
		return err
	}

	readme := "Deterministic Frontend Diagram Outputs\n\nGenerated by docflow frontend-diagrams from artifacts/frontend-page-architecture-tags.yaml.\n\nFiles:\n- 06-frontend-page-tag-architecture.generated.md\n"
	if err := os.WriteFile(filepath.Join(outputDir, "README.frontend.txt"), []byte(readme), 0o644); err != nil {
		return err
	}

	return nil
}

func renderADRToServices(adrs []adrLink) string {
	var b strings.Builder
	b.WriteString(renderDiagramFrontmatter(
		"DIA-ADR-SERVICES-GEN-001",
		"Generated ADR to Services Diagram",
		[]string{"ADR-INDEX-001"},
	))
	b.WriteString("# Diagram: ADR to Services\n\n")
	b.WriteString("```mermaid\nflowchart LR\n")
	for _, adr := range adrs {
		b.WriteString(fmt.Sprintf("  %s[%s]\n", safeID(adr.ADRID), adr.ADRID))
	}

	serviceSet := map[string]bool{}
	for _, adr := range adrs {
		for _, svc := range adr.LinkedServices {
			serviceSet[svc] = true
		}
	}
	services := mapKeysSorted(serviceSet)
	for _, svc := range services {
		b.WriteString(fmt.Sprintf("  %s[%s]\n", safeID(svc), svc))
	}
	for _, adr := range adrs {
		for _, svc := range sortedUnique(adr.LinkedServices) {
			b.WriteString(fmt.Sprintf("  %s --> %s\n", safeID(adr.ADRID), safeID(svc)))
		}
	}
	b.WriteString("```\n")
	return b.String()
}

func renderADRToSpecs(adrs []adrLink) string {
	var b strings.Builder
	b.WriteString(renderDiagramFrontmatter(
		"DIA-ADR-SPECS-GEN-001",
		"Generated ADR to Implemented Specs Diagram",
		[]string{"ADR-INDEX-001"},
	))
	b.WriteString("# Diagram: ADR to Implemented Specs\n\n")
	b.WriteString("```mermaid\nflowchart TB\n")
	for _, adr := range adrs {
		b.WriteString(fmt.Sprintf("  %s[%s]\n", safeID(adr.ADRID), adr.ADRID))
	}

	specSet := map[string]bool{}
	for _, adr := range adrs {
		for _, spec := range adr.ImplementsSpecs {
			specSet[spec] = true
		}
	}
	specs := mapKeysSorted(specSet)
	for _, spec := range specs {
		b.WriteString(fmt.Sprintf("  %s[%s]\n", safeID("SPEC-"+spec), spec))
	}
	for _, adr := range adrs {
		for _, spec := range sortedUnique(adr.ImplementsSpecs) {
			b.WriteString(fmt.Sprintf("  %s --> %s\n", safeID(adr.ADRID), safeID("SPEC-"+spec)))
		}
	}
	b.WriteString("```\n")
	return b.String()
}

func renderServiceDecisionHeatmap(adrs []adrLink) string {
	counts := map[string]int{}
	for _, adr := range adrs {
		for _, svc := range unique(adr.LinkedServices) {
			counts[svc]++
		}
	}
	services := make([]string, 0, len(counts))
	for svc := range counts {
		services = append(services, svc)
	}
	sort.Strings(services)

	var b strings.Builder
	b.WriteString(renderDiagramFrontmatter(
		"DIA-SERVICE-HEATMAP-GEN-001",
		"Generated Service Decision Heatmap",
		[]string{"ADR-INDEX-001"},
	))
	b.WriteString("# Diagram: Service Decision Heatmap\n\n")
	b.WriteString("```mermaid\nflowchart TB\n")
	for _, svc := range services {
		class := "Low"
		if counts[svc] >= 5 {
			class = "High"
		} else if counts[svc] >= 3 {
			class = "Medium"
		}
		b.WriteString(fmt.Sprintf("  %s[%s (%d ADRs)]:::%s\n", safeID(svc), svc, counts[svc], class))
	}
	b.WriteString("\n")
	b.WriteString("  classDef High fill:#f8d7da,stroke:#b02a37,stroke-width:2px;\n")
	b.WriteString("  classDef Medium fill:#fff3cd,stroke:#997404,stroke-width:2px;\n")
	b.WriteString("  classDef Low fill:#d1e7dd,stroke:#0f5132,stroke-width:2px;\n")
	b.WriteString("```\n")
	return b.String()
}

func renderReadme() string {
	var b strings.Builder
	b.WriteString(renderDiagramFrontmatter(
		"DOC-08-DIAGRAMS-GEN-README",
		"Deterministic Diagram Outputs",
		[]string{},
	))
	b.WriteString("# Deterministic Diagram Outputs\n\n")
	b.WriteString("Generated by `docflow diagrams` from `artifacts/adr-links.yaml`.\n\n")
	b.WriteString("Files:\n")
	b.WriteString("- `01-adr-to-services.md`\n")
	b.WriteString("- `02-adr-to-specs.md`\n")
	b.WriteString("- `03-service-decision-heatmap.md`\n")
	return b.String()
}

func renderFrontendPageTagArchitecture(nodes []frontendNode, sharedTags []string) string {
	var b strings.Builder
	b.WriteString(renderDiagramFrontmatter(
		"DIA-FRONTEND-PAGE-TAGS-GEN-001",
		"Generated Frontend Page Tag Architecture",
		[]string{"FEAT-FRONTEND-PAGE-REQS-001", "IMPL-FRONTEND-SHADCN-001", "GOV-FRONTEND-EVOLUTION-001"},
	))
	b.WriteString("# Generated Diagram: Frontend Page Tag Architecture\n\n")
	b.WriteString("```mermaid\ngraph TD\n")
	b.WriteString("  subgraph ShellPages\n")
	for _, node := range nodes {
		if hasTag(node.Tags, "shell") {
			b.WriteString(fmt.Sprintf("    %s[%s]\n", safeID(node.ID), node.ID))
		}
	}
	b.WriteString("  end\n\n")

	b.WriteString("  subgraph ModulePages\n")
	for _, node := range nodes {
		if hasTag(node.Tags, "module") {
			b.WriteString(fmt.Sprintf("    %s[%s]\n", safeID(node.ID), node.ID))
		}
	}
	b.WriteString("  end\n\n")

	tagSet := map[string]bool{}
	for _, tag := range sharedTags {
		tagSet[tag] = true
	}
	for _, node := range nodes {
		for _, tag := range node.Tags {
			tagSet[tag] = true
		}
	}
	tags := mapKeysSorted(tagSet)
	for _, tag := range tags {
		b.WriteString(fmt.Sprintf("  %s[(tag:%s)]\n", safeID("tag-"+tag), tag))
	}
	b.WriteString("\n")

	b.WriteString("  R1[[content+visual requirements]]\n")
	b.WriteString("  G1[[implementation guides]]\n\n")

	for _, node := range nodes {
		nodeID := safeID(node.ID)
		for _, tag := range sortedUnique(node.Tags) {
			b.WriteString(fmt.Sprintf("  %s --> %s\n", nodeID, safeID("tag-"+tag)))
		}
		if node.Links.ContentSpec != "" || node.Links.VisualSpec != "" {
			b.WriteString(fmt.Sprintf("  %s --> R1\n", nodeID))
		}
		if len(node.Links.ImplementationGuides) > 0 {
			b.WriteString(fmt.Sprintf("  %s --> G1\n", nodeID))
		}
	}
	b.WriteString("```\n\n")

	b.WriteString("## Page Linkage\n\n")
	b.WriteString("| Page ID | Content Spec | Visual Spec | Implementation Guides |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, node := range nodes {
		guides := strings.Join(sortedUnique(node.Links.ImplementationGuides), ", ")
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", node.ID, node.Links.ContentSpec, node.Links.VisualSpec, guides))
	}

	return b.String()
}

func hasTag(tags []string, expected string) bool {
	for _, tag := range tags {
		if tag == expected {
			return true
		}
	}
	return false
}

func safeID(value string) string {
	replacer := strings.NewReplacer("-", "_", "/", "_", ".", "_", " ", "_")
	return replacer.Replace(value)
}

func unique(values []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		if !seen[value] {
			seen[value] = true
			out = append(out, value)
		}
	}
	return out
}

func sortedUnique(values []string) []string {
	out := unique(values)
	sort.Strings(out)
	return out
}

func mapKeysSorted(items map[string]bool) []string {
	out := make([]string, 0, len(items))
	for key := range items {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

func renderDiagramFrontmatter(docID, title string, linkedIDs []string) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("doc_id: %s\n", docID))
	b.WriteString(fmt.Sprintf("title: %s\n", title))
	b.WriteString("doc_type: diagram\n")
	b.WriteString("concern: architecture\n")
	b.WriteString("status: accepted\n")
	b.WriteString("phase_scope:\n")
	b.WriteString("- MVP\n")
	b.WriteString("- Pilot\n")
	b.WriteString("- Production\n")
	b.WriteString("- Scale\n")
	b.WriteString("owner_role: principal_architect\n")
	b.WriteString("accountable_role: tech_lead\n")
	b.WriteString("reviewers:\n")
	b.WriteString("- service_owner\n")
	b.WriteString("tags:\n")
	b.WriteString("- ai-development\n")
	b.WriteString("- architecture\n")
	b.WriteString("- diagram\n")
	b.WriteString("- traceability\n")
	b.WriteString("linked_ids")
	if len(linkedIDs) == 0 {
		b.WriteString(": []\n")
	} else {
		b.WriteString(":\n")
		for _, linkedID := range linkedIDs {
			b.WriteString(fmt.Sprintf("- %s\n", linkedID))
		}
	}
	b.WriteString("review_cadence: monthly\n")
	b.WriteString("source_of_truth: true\n")
	b.WriteString("version: '1.0'\n")
	b.WriteString("specificity: platform-shared\n")
	b.WriteString("---\n\n")
	return b.String()
}
